config/routes.rb
Rails.application.routes.draw do
 root "employees#index"

 resources :employees
 # post "employees/new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
	validates :name, presence: true
    validates :city, presence: true
    validates :designation, presence: true

    before_save :downcase_fields

    def downcase_fields
      self.designation.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def show
    # binding.pry
    @employee = Employee.find(params[:id])
  end

  def new
    # binding.pry
    @employee = Employee.new
  end

  def create
    # binding.pry
    @employee = Employee.new(employee_params)
    if @employee.save
      flash[:notice] = "Employee detail '#{@employee.name}' has been created successfully."
      redirect_to employees_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])

    if @employee.update(employee_params)
      flash[:notice] = "Employee detail '#{@employee.id}' has been Updated successfully."
      redirect_to employees_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

   def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    flash[:notice] = "Employee detail '#{@employee.name}' has been deleted successfully."
    redirect_to root_path, status: :see_other
  end

  private
  def employee_params
    # binding.pry
    params.require(:employee).permit(:name, :city, :designation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with model: @employee do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @employee.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :city %><br>
    <%= form.text_field :city %>
    <% @employee.errors.full_messages_for(:city).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :designation %><br>
    <%= form.text_field :designation %>
    <% @employee.errors.full_messages_for(:designation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @employee %>

app/views/employees/index.html.erb
<% flash.each do |type, msg| %>
  <div style="color:green; font-size: 30px;">
    <%= msg %>
  </div>
<% end %>
<h1>Employees Details</h1>

<ul>
  <% @employees.each do |emps| %>
    <li>
      <%= link_to emps.id, emps %>
    </li>
  <% end %>
</ul>

<%= link_to "Create Employee", new_employee_path %>

app/views/employees/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @employee %>

app/views/employees/show.html.erb
<h1>Employee Deatils is</h1>

<h3 style="color: blue;">Id = <%= @employee.id %></h1>

<h3 style="color: red;">Name = <%= @employee.name %></h3>

<h3 style="color: red">City = <%= @employee.city %></h3>

<h3 style="color: green;">City = <%= @employee.designation %></h3>


<ul>
  <li><%= link_to "Edit", edit_employee_path(@employee) %></li>
</ul>

<li><%= link_to "Delete Employee", employee_path(@employee), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>